<?php

/**
 * ModxWebUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWebUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWebUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWebUsers');
    }
}