<?php

/**
 * ModxWebUserAttributesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWebUserAttributesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWebUserAttributesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWebUserAttributes');
    }
}