<?php

/**
 * ModxManagerLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxManagerLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxManagerLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxManagerLog');
    }
}