<?php

/**
 * ModxSiteKeywordsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteKeywordsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteKeywordsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteKeywords');
    }
}