<?php

/**
 * ModxSiteTmplvarTemplatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteTmplvarTemplatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteTmplvarTemplatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteTmplvarTemplates');
    }
}