<?php

/**
 * ModxSitePluginEventsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSitePluginEventsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSitePluginEventsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSitePluginEvents');
    }
}