<?php

/**
 * ModxSiteTmplvarContentvaluesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteTmplvarContentvaluesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteTmplvarContentvaluesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteTmplvarContentvalues');
    }
}