<?php

/**
 * ModxEventLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxEventLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxEventLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxEventLog');
    }
}