<?php

/**
 * ModxWorkshopagendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWorkshopagendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWorkshopagendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWorkshopagenda');
    }
}