<?php

/**
 * ModxSiteMetatagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteMetatagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteMetatagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteMetatags');
    }
}