<?php

/**
 * ModxManagerUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxManagerUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxManagerUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxManagerUsers');
    }
}