<?php

/**
 * ModxSiteSnippetsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteSnippetsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteSnippetsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteSnippets');
    }
}