<?php

/**
 * ModxMembergroupAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxMembergroupAccessTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxMembergroupAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxMembergroupAccess');
    }
}