<?php

/**
 * ModxUserSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxUserSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxUserSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxUserSettings');
    }
}