<?php

/**
 * ModxSiteTemplatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteTemplatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteTemplatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteTemplates');
    }
}