<?php

/**
 * ModxWebgroupNamesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWebgroupNamesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWebgroupNamesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWebgroupNames');
    }
}