<?php

/**
 * ModxJotContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxJotContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxJotContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxJotContent');
    }
}