<?php

/**
 * ModxActiveUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxActiveUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxActiveUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxActiveUsers');
    }
}