<?php

/**
 * ModxSiteModuleAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteModuleAccessTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteModuleAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteModuleAccess');
    }
}