<?php

/**
 * ModxWorkshopagendaitemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWorkshopagendaitemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWorkshopagendaitemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWorkshopagendaitem');
    }
}