<?php

/**
 * ModxSiteModulesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteModulesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteModulesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteModules');
    }
}