<?php

/**
 * ModxMembergroupNamesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxMembergroupNamesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxMembergroupNamesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxMembergroupNames');
    }
}