<?php

/**
 * ModxJotSubscriptionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxJotSubscriptionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxJotSubscriptionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxJotSubscriptions');
    }
}