<?php

/**
 * ModxSiteHtmlsnippetsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteHtmlsnippetsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteHtmlsnippetsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteHtmlsnippets');
    }
}