<?php

/**
 * ModxWebgroupAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWebgroupAccessTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWebgroupAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWebgroupAccess');
    }
}