<?php

/**
 * ModxUserextendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxUserextendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxUserextendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxUserextend');
    }
}