<?php

/**
 * ModxSiteModuleDepobjTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteModuleDepobjTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteModuleDepobjTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteModuleDepobj');
    }
}