<?php

/**
 * ModxUserRolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxUserRolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxUserRolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxUserRoles');
    }
}