<?php

/**
 * ModxWorkshopregisterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWorkshopregisterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWorkshopregisterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWorkshopregister');
    }
}