<?php

/**
 * ModxWebUserSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWebUserSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWebUserSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWebUserSettings');
    }
}