<?php

/**
 * ModxSiteContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteContent');
    }
}