<?php

/**
 * ModxSystemSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSystemSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSystemSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSystemSettings');
    }
}