<?php

/**
 * ModxKeywordXrefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxKeywordXrefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxKeywordXrefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxKeywordXref');
    }
}