<?php

/**
 * ModxDocumentgroupNamesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxDocumentgroupNamesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxDocumentgroupNamesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxDocumentgroupNames');
    }
}