<?php

/**
 * ModxEntityseekerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxEntityseekerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxEntityseekerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxEntityseeker');
    }
}