<?php

/**
 * ModxUserMessagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxUserMessagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxUserMessagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxUserMessages');
    }
}