<?php

/**
 * ModxSitePluginsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSitePluginsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSitePluginsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSitePlugins');
    }
}