<?php

/**
 * ModxDocumentGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxDocumentGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxDocumentGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxDocumentGroups');
    }
}