<?php

/**
 * ModxEntityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxEntityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxEntityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxEntity');
    }
}