<?php

/**
 * ModxSiteTmplvarsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteTmplvarsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteTmplvarsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteTmplvars');
    }
}