<?php

/**
 * ModxSystemEventnamesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSystemEventnamesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSystemEventnamesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSystemEventnames');
    }
}