<?php

/**
 * ModxTrainerinfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxTrainerinfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxTrainerinfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxTrainerinfo');
    }
}