<?php

/**
 * ModxWorkshopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWorkshopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWorkshopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWorkshop');
    }
}