<?php

/**
 * ModxWorkshopregisteruserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWorkshopregisteruserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWorkshopregisteruserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWorkshopregisteruser');
    }
}