<?php

/**
 * ModxSiteContentMetatagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxSiteContentMetatagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxSiteContentMetatagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxSiteContentMetatags');
    }
}