<?php

/**
 * ModxMemberGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxMemberGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxMemberGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxMemberGroups');
    }
}