<?php

/**
 * ModxUserAttributesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxUserAttributesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxUserAttributesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxUserAttributes');
    }
}