<?php

/**
 * ModxEntitytrainerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxEntitytrainerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxEntitytrainerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxEntitytrainer');
    }
}