<?php

/**
 * ModxJotFieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxJotFieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxJotFieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxJotFields');
    }
}