<?php

/**
 * ModxCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxCountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxCountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxCountry');
    }
}