<?php

/**
 * ModxWebGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModxWebGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModxWebGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModxWebGroups');
    }
}