<?php

require_once("BaseModxWebGroups.php");
require_once("ModxWebgroupNames.php");
require_once("ModxWebgroupAccess.php");
/**
 * ModxWebGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ModxWebGroups extends BaseModxWebGroups
{
  public function setUp()
	{
		$this->hasOne('ModxWebgroupNames as GroupName', array(
			'local' => 'webgroup',
			'foreign' => 'id'
			)
		);

    $this->hasMany('ModxWebgroupAccess as GroupAccess', array(
			'local' => 'webgroup',
			'foreign' => 'webgroup'
			)
		);
  }
}